from src.models.config_models import (Chatbot_config, Storage_DB_config, RAG_DB_config, Embedder_config)
from src.models.data_models import (RAG_DTModel, Storage_DTModel)

from src.managers.DB_managers import (Storage_DB_manager, RAG_DB_manager)
from src.managers.embedding_managers import Embedding_manager
from src.managers.chatBot_managers import ChatBot_manager



#TODO(FIX): Implement a check to make sure that new embeddings ain't going to create incongruence
#               (mixed vector types in the same collection)
class Manager_coordinator:
    """
    General manager orchestrating other managers in order to permit strict collaboration between managers
        while avoiding horizontal and cyclic dependencies.
    It also permits to check incongruent configurations between managers.
    """
    def __init__(self, storage_conf: Storage_DB_config, rag_conf: RAG_DB_config,
                 embedder_config: Embedder_config, chatbot_config: Chatbot_config,
                 default_RAG_DB_index_name: str, default_Storage_DB_collection_name: str):
        self.storage_DB_manager = Storage_DB_manager(storage_conf)
        self.rag_DB_manager= RAG_DB_manager(rag_conf)
        self.embedding_manager= Embedding_manager(embedder_config)
        self.chatbot_manager= ChatBot_manager(chatbot_config)

        self.default_RAG_DB_index_name = default_RAG_DB_index_name
        self.default_Storage_DB_collection_name = default_Storage_DB_collection_name


    #TODO(UPDATE): make method 'from storage DB' instead 'from URLs'
    def ingest_documents_from_urls(self, file_URLs: list[str], 
                                   target_index_name: str = None) -> tuple[bool, list[str]]:
        """
        Generates embeddings from a list of file URLs and stores them in the RAG database.
        Parameters:
            file_URLs (list[str]): A list of URLs leading to the files to embed and store.
            target_index_name (str): The name of the target index in the RAG database where to store the embeddings.
                                     If not provided, the default index name is used.
        Returns:
            tuple[bool,list[str]]: A tuple where the first element is the overall success status,
                                        and the second element is a list of failed URLs (if any).
                                    NOTE: If the first element is True, the second element will be an empty list.
        """
        if target_index_name is None:
            target_index_name = self.default_RAG_DB_index_name

        failed_URLs: list[str] = []

        for file_URL in file_URLs:
            try:
                embeddings: list[RAG_DTModel] = self.embedding_manager.generate_embeddings_from_URL(file_URL)
                self.rag_DB_manager.insert_records(target_collection_name=target_index_name, data_models=embeddings)
            except Exception as e:
                print(f"Failed to process URL {file_URL}: {str(e)}") #TODO(polishing): consider another logging method
                failed_URLs.append(file_URL)

        overall_success: bool = len(failed_URLs) == 0
        return (overall_success, failed_URLs)
    

    def reply_to_question(self, question: str) -> str:
        """
        Retrieves an answer to a question using the RAG database and the chatbot manager.
        Parameters:
            question (str): The question to be answered.
        Returns:
            str: The answer generated by the chatbot manager.
        """
        retrieved_texts: list[str] = [ dataModel.text for dataModel in self.reply_to_question_raw_response(question) ]
        return self.chatbot_manager.send_message_with_responseInfo(question, retrieved_texts)
    

    def reply_to_question_raw_response(self, question: str) -> list[RAG_DTModel]:
        """
        Retrieves raw results from the RAG database based on a question.
        Parameters:
            question (str): The question to query the RAG database with.
        Returns:
            any: The raw results retrieved from the RAG database.
        """
        vector_query = self.embedding_manager.generate_vector_query_from_text(question)
        return self.rag_DB_manager.retrieve_vectors_using_vectorQuery(vector_query)
    

    def disconnect_all_managers(self) -> None:
        """
        Disconnects all managed database connections.
        """
        self.storage_DB_manager.disconnect()
        self.rag_DB_manager.disconnect()
        self.embedding_manager.disconnect()
        self.chatbot_manager.disconnect()